### ISSUE TITLE
older tasmotas fail due different answer format

### ISSUE THREAD

**Issue by ikke-t** [tobias-richter/ansible-tasmota#18]
Hi,

first of all, thanks for doing the role, looks really nice. I have a bunch of tasmota devices at home, and immediately went and tried this role. However, I noticed it won't work for the older modules that I have. At least that's what I thinki is the reason. The module get's some sort of wrong answer for the status query at the beginning. So perhaps it would be good to have some version check or something? Or handle different answers differently?

It seems to come down to this difference in answer:

```
╰─$ curl http://sonoff-rv/cm\?cmnd\=poweronstate
{"PowerOnState":1}

╰─$ curl http://sonoff-tp/cm\?cmnd\=poweronstate
RESULT = {"PowerOnState":1}
```
I don't know exactly when the format has changed, but seems the older ones have "RESULT = " before the json. This fails the role. I just went to try OTA update to one of my tasmota light swithces, but it died during the process.... I'll report back if I get it back alive one day. The version was 5.11.

**Comment by deveth0** [comment]
Yeah, the api is a bit inconsistent. There was also a bug in one of the early 9.x versions, that the returned GPIO json was invalid.

I never tested with < 9.x, so can't provide any input here, but there are some upgrade nodes available:
https://tasmota.github.io/docs/Upgrading/

**Comment by tobias-richter** [comment]
@ikke-t have a look at: https://github.com/reloxx13/TasmoAdmin
This makes it much easier to manage the update of a large amount of tasmota devices.
In Home Assistant this can be easily installed as an addon.

**Comment by tobias-richter** [comment]
@ikke-t closing this since there was no answer. Feel free to open again.
